# Generated by Django 6.0.2 on 2026-02-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReViveLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(max_length=20, unique=True)),
                ('device_id', models.CharField(max_length=50)),
                ('installed_at', models.DateTimeField()),
                ('location_text', models.CharField(max_length=200)),
                ('efficiency_percent', models.IntegerField(default=92)),
                ('battery_health_percent', models.IntegerField(default=87)),
                ('co2_saved_kg', models.FloatField(default=420.0)),
                ('carbon_credits', models.FloatField(default=0.42)),
                ('carbon_value_inr', models.IntegerField(default=210)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('tender_reference', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
