# Generated by Django 6.0.2 on 2026-02-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ReViveLight',
        ),
    ]
